name: Linux Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        javafx: true
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle (jlink)
      run: ./gradlew jlink
     
    - name: Pack release
      run: zip -r hugrade_release_linux.zip ./build/image
                
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: hugrade_release_linux.zip
        allowUpdates: true
        tag: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
