name: Linux Release

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        javafx: true
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Execute Unit Tests
      run: |
        ./gradlew hugrade_core:test
        ./gradlew hugrade_data:test
        ./gradlew hugrade_fx:test
      
    - name: Build with Gradle (jlink)
      run: ./gradlew jlink
     
    - name: Pack release
      run: zip -r hugrade_release_linux.zip ./hugrade_fx/build/image
                
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: hugrade_release_linux.zip
        allowUpdates: true
        tag: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
